version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=BASE_DATOS_HYDROM
      - POSTGRES_USER=carlos
      - POSTGRES_PASSWORD=calidad1
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=rodriguezcarlos.cdr@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=calidad1
    ports:
      - 5050:80



